export const availableServices = [
  { id: 'googletagmanager', name: 'Google Tag Manager', category: 'analytics' },
  { id: 'googleanalytics', name: 'Google Analytics (GA4)', category: 'analytics' },
  { id: 'gtag', name: 'Google Analytics (gtag.js)', category: 'analytics' },
  { id: 'matomocloud', name: 'Matomo Cloud', category: 'analytics' },
  { id: 'matomo', name: 'Matomo (Self-hosted)', category: 'analytics' },
  { id: 'plausible', name: 'Plausible Analytics', category: 'analytics' },
  { id: 'fathom', name: 'Fathom Analytics', category: 'analytics' },
  { id: 'clarity', name: 'Microsoft Clarity', category: 'analytics' },
  { id: 'hotjar', name: 'Hotjar', category: 'analytics' },
  { id: 'facebook', name: 'Facebook Pixel', category: 'ads' },
  { id: 'facebookconversions', name: 'Facebook Conversions API', category: 'ads' },
  { id: 'linkedin', name: 'LinkedIn Insights', category: 'ads' },
  { id: 'twitter', name: 'Twitter/X Pixel', category: 'ads' },
  { id: 'tiktok', name: 'TikTok Pixel', category: 'ads' },
  { id: 'pinterest', name: 'Pinterest Tag', category: 'ads' },
  { id: 'googlepublishertaggpt', name: 'Google Publisher Tag (GPT)', category: 'ads' },
  { id: 'googleadsremarketing', name: 'Google Ads Remarketing', category: 'ads' },
  { id: 'googleadsconversion', name: 'Google Ads Conversion', category: 'ads' },
  { id: 'youtube', name: 'YouTube', category: 'video' },
  { id: 'vimeo', name: 'Vimeo', category: 'video' },
  { id: 'dailymotion', name: 'Dailymotion', category: 'video' },
  { id: 'recaptcha', name: 'Google reCAPTCHA', category: 'security' },
  { id: 'hcaptcha', name: 'hCaptcha', category: 'security' },
  { id: 'stripe', name: 'Stripe', category: 'payment' },
  { id: 'paypal', name: 'PayPal', category: 'payment' },
  { id: 'intercom', name: 'Intercom', category: 'support' },
  { id: 'zendesk', name: 'Zendesk', category: 'support' },
  { id: 'crisp', name: 'Crisp', category: 'support' },
  { id: 'hubspot', name: 'HubSpot', category: 'support' },
  { id: 'tawk', name: 'Tawk.to', category: 'support' },
  { id: 'disqus', name: 'Disqus', category: 'comment' },
  { id: 'facebooklikebox', name: 'Facebook Like Box', category: 'social' },
  { id: 'twitter', name: 'Twitter Widget', category: 'social' },
  { id: 'instagram', name: 'Instagram Widget', category: 'social' },
  { id: 'shareaholic', name: 'Shareaholic', category: 'social' },
  { id: 'addthis', name: 'AddThis', category: 'social' },
  { id: 'googlemaps', name: 'Google Maps', category: 'api' },
  { id: 'openstreetmap', name: 'OpenStreetMap', category: 'api' },
  { id: 'googlefonts', name: 'Google Fonts', category: 'api' },
  { id: 'typekit', name: 'Adobe Fonts (Typekit)', category: 'api' }
];

export const serviceCategories = [
  { id: 'analytics', name: 'Analytics', icon: '📊' },
  { id: 'ads', name: 'Publicité', icon: '📢' },
  { id: 'video', name: 'Vidéo', icon: '🎥' },
  { id: 'security', name: 'Sécurité', icon: '🔒' },
  { id: 'payment', name: 'Paiement', icon: '💳' },
  { id: 'support', name: 'Support', icon: '💬' },
  { id: 'comment', name: 'Commentaires', icon: '💭' },
  { id: 'social', name: 'Réseaux Sociaux', icon: '👥' },
  { id: 'api', name: 'API & Services', icon: '🔌' }
];
