export const availableServices = [
  { id: 'googletagmanager', name: 'Google Tag Manager', category: 'analytics' },
  { id: 'googleanalytics', name: 'Google Analytics (GA4)', category: 'analytics' },
  { id: 'gtag', name: 'Google Analytics (gtag.js)', category: 'analytics' },
  { id: 'matomocloud', name: 'Matomo Cloud', category: 'analytics' },
  { id: 'matomo', name: 'Matomo (Self-hosted)', category: 'analytics' },
  { id: 'plausible', name: 'Plausible Analytics', category: 'analytics' },
  { id: 'fathom', name: 'Fathom Analytics', category: 'analytics' },
  { id: 'clarity', name: 'Microsoft Clarity', category: 'analytics' },
  { id: 'hotjar', name: 'Hotjar', category: 'analytics' },
  { id: 'mixpanel', name: 'Mixpanel', category: 'analytics' },
  { id: 'amplitude', name: 'Amplitude', category: 'analytics' },
  { id: 'segment', name: 'Segment', category: 'analytics' },
  { id: 'heap', name: 'Heap Analytics', category: 'analytics' },
  { id: 'fullstory', name: 'FullStory', category: 'analytics' },
  { id: 'kissmetrics', name: 'KISSmetrics', category: 'analytics' },
  { id: 'crazyegg', name: 'Crazy Egg', category: 'analytics' },
  { id: 'mouseflow', name: 'Mouseflow', category: 'analytics' },
  { id: 'statcounter', name: 'StatCounter', category: 'analytics' },
  { id: 'clicky', name: 'Clicky', category: 'analytics' },
  { id: 'woopra', name: 'Woopra', category: 'analytics' },
  { id: 'facebook', name: 'Facebook Pixel', category: 'ads' },
  { id: 'facebookconversions', name: 'Facebook Conversions API', category: 'ads' },
  { id: 'linkedin', name: 'LinkedIn Insights', category: 'ads' },
  { id: 'twitter', name: 'Twitter/X Pixel', category: 'ads' },
  { id: 'tiktok', name: 'TikTok Pixel', category: 'ads' },
  { id: 'pinterest', name: 'Pinterest Tag', category: 'ads' },
  { id: 'snapchat', name: 'Snapchat Pixel', category: 'ads' },
  { id: 'reddit', name: 'Reddit Pixel', category: 'ads' },
  { id: 'quora', name: 'Quora Pixel', category: 'ads' },
  { id: 'taboola', name: 'Taboola', category: 'ads' },
  { id: 'outbrain', name: 'Outbrain', category: 'ads' },
  { id: 'bingads', name: 'Microsoft Advertising', category: 'ads' },
  { id: 'criteo', name: 'Criteo', category: 'ads' },
  { id: 'googlepublishertaggpt', name: 'Google Publisher Tag (GPT)', category: 'ads' },
  { id: 'googleadsremarketing', name: 'Google Ads Remarketing', category: 'ads' },
  { id: 'googleadsconversion', name: 'Google Ads Conversion', category: 'ads' },
  { id: 'googledoubleclick', name: 'Google DoubleClick', category: 'ads' },
  { id: 'adroll', name: 'AdRoll', category: 'ads' },
  { id: 'amazonpublisher', name: 'Amazon Publisher Services', category: 'ads' },
  { id: 'youtube', name: 'YouTube', category: 'video' },
  { id: 'vimeo', name: 'Vimeo', category: 'video' },
  { id: 'dailymotion', name: 'Dailymotion', category: 'video' },
  { id: 'twitch', name: 'Twitch', category: 'video' },
  { id: 'wistia', name: 'Wistia', category: 'video' },
  { id: 'vidyard', name: 'Vidyard', category: 'video' },
  { id: 'brightcove', name: 'Brightcove', category: 'video' },
  { id: 'recaptcha', name: 'Google reCAPTCHA', category: 'security' },
  { id: 'hcaptcha', name: 'hCaptcha', category: 'security' },
  { id: 'cloudflare', name: 'Cloudflare Turnstile', category: 'security' },
  { id: 'stripe', name: 'Stripe', category: 'payment' },
  { id: 'paypal', name: 'PayPal', category: 'payment' },
  { id: 'braintree', name: 'Braintree', category: 'payment' },
  { id: 'square', name: 'Square', category: 'payment' },
  { id: 'adyen', name: 'Adyen', category: 'payment' },
  { id: 'mollie', name: 'Mollie', category: 'payment' },
  { id: 'klarna', name: 'Klarna', category: 'payment' },
  { id: 'intercom', name: 'Intercom', category: 'support' },
  { id: 'zendesk', name: 'Zendesk', category: 'support' },
  { id: 'crisp', name: 'Crisp', category: 'support' },
  { id: 'hubspot', name: 'HubSpot', category: 'support' },
  { id: 'tawk', name: 'Tawk.to', category: 'support' },
  { id: 'drift', name: 'Drift', category: 'support' },
  { id: 'livechat', name: 'LiveChat', category: 'support' },
  { id: 'freshchat', name: 'Freshchat', category: 'support' },
  { id: 'tidio', name: 'Tidio', category: 'support' },
  { id: 'usercom', name: 'User.com', category: 'support' },
  { id: 'customerio', name: 'Customer.io', category: 'support' },
  { id: 'olark', name: 'Olark', category: 'support' },
  { id: 'disqus', name: 'Disqus', category: 'comment' },
  { id: 'commento', name: 'Commento', category: 'comment' },
  { id: 'graphcomment', name: 'GraphComment', category: 'comment' },
  { id: 'hyvor', name: 'Hyvor Talk', category: 'comment' },
  { id: 'facebookcomments', name: 'Facebook Comments', category: 'comment' },
  { id: 'facebooklikebox', name: 'Facebook Like Box', category: 'social' },
  { id: 'twitterwidget', name: 'Twitter Widget', category: 'social' },
  { id: 'instagram', name: 'Instagram Widget', category: 'social' },
  { id: 'linkedinbadge', name: 'LinkedIn Badge', category: 'social' },
  { id: 'shareaholic', name: 'Shareaholic', category: 'social' },
  { id: 'addthis', name: 'AddThis', category: 'social' },
  { id: 'sharethis', name: 'ShareThis', category: 'social' },
  { id: 'addtoany', name: 'AddToAny', category: 'social' },
  { id: 'socialsnap', name: 'Social Snap', category: 'social' },
  { id: 'googlemaps', name: 'Google Maps', category: 'api' },
  { id: 'openstreetmap', name: 'OpenStreetMap', category: 'api' },
  { id: 'mapbox', name: 'Mapbox', category: 'api' },
  { id: 'googlefonts', name: 'Google Fonts', category: 'api' },
  { id: 'typekit', name: 'Adobe Fonts (Typekit)', category: 'api' },
  { id: 'cloudflarecdn', name: 'Cloudflare CDN', category: 'api' },
  { id: 'jsdelivr', name: 'jsDelivr CDN', category: 'api' },
  { id: 'unpkg', name: 'UNPKG CDN', category: 'api' },
  { id: 'cdnjs', name: 'cdnjs', category: 'api' },
  { id: 'jsdelivr', name: 'jsDelivr', category: 'api' },
  { id: 'sendgrid', name: 'SendGrid', category: 'email' },
  { id: 'mailchimp', name: 'Mailchimp', category: 'email' },
  { id: 'sendinblue', name: 'Brevo (Sendinblue)', category: 'email' },
  { id: 'klaviyo', name: 'Klaviyo', category: 'email' },
  { id: 'activecampaign', name: 'ActiveCampaign', category: 'email' },
  { id: 'convertkit', name: 'ConvertKit', category: 'email' },
  { id: 'mailerlite', name: 'MailerLite', category: 'email' },
  { id: 'getresponse', name: 'GetResponse', category: 'email' },
  { id: 'aweber', name: 'AWeber', category: 'email' },
  { id: 'constantcontact', name: 'Constant Contact', category: 'email' },
  { id: 'optimizely', name: 'Optimizely', category: 'optimization' },
  { id: 'vwo', name: 'VWO', category: 'optimization' },
  { id: 'abtasty', name: 'AB Tasty', category: 'optimization' },
  { id: 'googleoptimize', name: 'Google Optimize', category: 'optimization' },
  { id: 'unbounce', name: 'Unbounce', category: 'optimization' },
  { id: 'instapage', name: 'Instapage', category: 'optimization' },
  { id: 'sentry', name: 'Sentry', category: 'monitoring' },
  { id: 'bugsnag', name: 'Bugsnag', category: 'monitoring' },
  { id: 'rollbar', name: 'Rollbar', category: 'monitoring' },
  { id: 'raygun', name: 'Raygun', category: 'monitoring' },
  { id: 'newrelic', name: 'New Relic', category: 'monitoring' },
  { id: 'datadog', name: 'Datadog', category: 'monitoring' },
  { id: 'logrocket', name: 'LogRocket', category: 'monitoring' },
  { id: 'trustpilot', name: 'Trustpilot', category: 'review' },
  { id: 'yotpo', name: 'Yotpo', category: 'review' },
  { id: 'feefo', name: 'Feefo', category: 'review' },
  { id: 'reviews', name: 'Reviews.io', category: 'review' },
  { id: 'bazaarvoice', name: 'Bazaarvoice', category: 'review' }
];

export const serviceCategories = [
  { id: 'analytics', name: 'Analytics', icon: '📊' },
  { id: 'ads', name: 'Publicité', icon: '📢' },
  { id: 'video', name: 'Vidéo', icon: '🎥' },
  { id: 'security', name: 'Sécurité', icon: '🔒' },
  { id: 'payment', name: 'Paiement', icon: '💳' },
  { id: 'support', name: 'Support', icon: '💬' },
  { id: 'comment', name: 'Commentaires', icon: '💭' },
  { id: 'social', name: 'Réseaux Sociaux', icon: '👥' },
  { id: 'api', name: 'API & Services', icon: '🔌' },
  { id: 'email', name: 'Email Marketing', icon: '📧' },
  { id: 'optimization', name: 'Optimisation', icon: '🎯' },
  { id: 'monitoring', name: 'Monitoring', icon: '🔍' },
  { id: 'review', name: 'Avis clients', icon: '⭐' }
];
